### ISSUE TITLE
Filters to implement

### ISSUE THREAD

**Issue by hageldave** [hageldave/ImagingKit#9]
### Point Operations
- [ ] Generic Affine Transformation `g(x,y) = a * f(x,y) + b `
- [x] Greyscale
- [ ] Contrast
- [x] Generic Function Transformation `g(x,y) = h( f(x,y) ) `
- [x] Gamma Correction
- [x] Histogram Equalisation
- [ ] Thresholding (Black&White)

### Convolution Filters
- [x] Generic Convolution by Kernel
- [x] Gaussian
- [x] Difference of Gaussians (DOG)
- [ ] Sobel
- [ ] Directional (Motion) Blur

### Morphological Filters
- [ ] Dilation
- [ ] Erosion
- [ ] Opening
- [ ] Closing
- [ ] Median

### Mixed Methods
- [ ] Canny Edge Detector

### Variational Methods
- [ ] Mumford-Shah Segmentation
... well this stuff is not light, lets see ...

**Comment by SadatAnwar** [comment]
This looks like a fun list to implement. I will pick up one as soon as I have time time (this week or the next (moving apartments this week)).

**Comment by hageldave** [comment]
@SadatAnwar I just deployed the latest release of the core artifact (1.4) and updated the filter project to depend on the latest version. Now you can find this `hageldave.imagingkit.core.util.ImageFrame.display(img)` in the core artifact, which will probably be handy for implementing stuff.
I'm trying to test the basic interfaces of the filter artifact and write javadocs asap ;)

**Comment by SadatAnwar** [comment]
Hey @hageldave sorry for my inactive sprint after just once commit, first I was moving apartments, and then now I fell sick! I really want to get to this as soon as I can. Maybe in the mean time, if you need me to review stuff, just ping me, maybe that Ill do more easily. In any case, I will mark items I am working on, as soon as I start, so we dont waste time on the same filter.

**Comment by hageldave** [comment]
@SadatAnwar no worries, I just wanted to give you the update. There is no hurry at all, take your time, I may be more active now since there is no Uni currently ^^

**Comment by hageldave** [comment]
Generic Function Transformation implemented in  [GenericColorChannelTransformation](https://github.com/hageldave/ImagingKit/blob/devel/ImagingKit_Filter/src/main/java/hageldave/imagingkit/filter/implementations/GenericColorChannelTransformation.java)

**Comment by hageldave** [comment]
further filter implementation is postponed until the release of version 2.0 of imagingkit core
